"""
This is a setup.py script generated by py2applet
bla bla
Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['bfMonitor.py']
DATA_FILES = ['data.db']
OPTIONS = {'packages': ['model']}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app', 'requests'],
)
